"""
FinMate AI — store.py
Simple JSON file-based data store.

This module handles all reading/writing of finance data to a local
JSON file. It acts as a lightweight database so the app works
without any external database setup.

Data shape stored in finmate_data.json:
{
    "income": 0.0,
    "expenses": [
        {
            "id": "abc123",
            "name": "Groceries",
            "amount": 150.0,
            "category": "Food & Dining",
            "created_at": 1724000000.0
        },
        ...
    ]
}
"""

import json
import os
from pathlib import Path

# Path to the JSON data file (lives next to this script)
DATA_FILE = Path(__file__).parent / "finmate_data.json"

# Default state when no data file exists yet
DEFAULT_DATA = {
    "income": 0.0,
    "expenses": [],
}


def _read_file() -> dict:
    """Read the JSON data file and return its contents as a dict.

    If the file doesn't exist or is corrupted, return DEFAULT_DATA.
    """
    if not DATA_FILE.exists():
        return DEFAULT_DATA.copy()

    try:
        with open(DATA_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)

        # Basic validation: make sure the shape is correct
        if not isinstance(data.get("income"), (int, float)):
            data["income"] = 0.0
        if not isinstance(data.get("expenses"), list):
            data["expenses"] = []

        return data

    except (json.JSONDecodeError, OSError):
        # If file is corrupted, start fresh
        return DEFAULT_DATA.copy()


def _write_file(data: dict) -> None:
    """Write the given dict to the JSON data file."""
    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


# ──────────────────────────────────────────────
# Public API — these functions are used by main.py
# ──────────────────────────────────────────────

def get_income() -> float:
    """Return the current monthly income."""
    return _read_file()["income"]


def set_income(amount: float) -> float:
    """Update and return the monthly income."""
    data = _read_file()
    data["income"] = amount
    _write_file(data)
    return data["income"]


def get_expenses() -> list[dict]:
    """Return all expenses as a list of dicts."""
    return _read_file()["expenses"]


def add_expense(expense: dict) -> dict:
    """Add a new expense and return it.

    The expense dict should already have an 'id' and 'created_at'
    generated by the caller (main.py).
    """
    data = _read_file()
    data["expenses"].append(expense)
    _write_file(data)
    return expense


def delete_expense(expense_id: str) -> bool:
    """Delete an expense by its id.

    Returns True if the expense was found and deleted,
    False if no expense with that id exists.
    """
    data = _read_file()
    original_count = len(data["expenses"])

    # Keep only expenses whose id does NOT match
    data["expenses"] = [
        exp for exp in data["expenses"] if exp["id"] != expense_id
    ]

    if len(data["expenses"]) == original_count:
        return False  # Nothing was removed

    _write_file(data)
    return True
